config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :posts do
    member do
      get 'apply', to: 'posts#apply'
      post 'confirm', to: 'posts#confirm'
      get 'confirm', to: 'posts#confirm'
      get 'purchase', to: 'posts#purchase'
    end
  end
  resources :messages
  resources :users, only: [:edit, :update, :show]
  resources :cards, only: [:new, :create, :edit, :update, :show]
  resources :groups, only: [:index, :new, :create, :edit, :update] do
    resources :messages
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages
  validates :name, presence: true, uniqueness: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :content, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :content, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true
  
  has_many :posts
  has_many :cards
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :nickname])
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require "payjp"
  before_action :set_card

  def new # カードの登録画面。送信ボタンを押すとcreateアクションへ。
    card = Card.where(user_id: current_user.id).first
    redirect_to action: "index" if card.present?
  end

  # indexアクションはここでは省略

  def create #PayjpとCardのデータベースを作成
    Payjp.api_key = '秘密鍵'

    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      # トークンが正常に発行されていたら、顧客情報をPAY.JPに登録します。
      customer = Payjp::Customer.create(
        description: 'test', # 無くてもOK。PAY.JPの顧客情報に表示する概要です。
        email: current_user.email,
        card: params['payjp-token'], # 直前のnewアクションで発行され、送られてくるトークンをここで顧客に紐付けて永久保存します。
        metadata: {user_id: current_user.id} # 無くてもOK。
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "index"
      else
        redirect_to action: "create"
      end
    end
  end

  private

  def set_card
    @card = Card.where(user_id: current_user.id).first if Card.where(user_id: current_user.id).present?
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to root_path, notice: 'グループを更新しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

  def set_group
    @group = Group.find(params[:id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      redirect_to group_messages_path, notice: 'メッセージが送信されました'
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private
  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  require 'payjp'

  def index
    @posts = Post.includes(:user)
  end

  def new
    @post = Post.new
  end

  def create
    Post.create(post_params)
    redirect_to root_path
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to post_path(post.id)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end

  def apply
    @post = Post.includes(:user).find(params[:id])
  end

  def confirm
    
  end

  def purchase
    Payjp.api_key = "秘密鍵"
    Payjp::Charge.create(
      amount: 777, # 決済する値段
      card: params['payjp-token'], # フォームを送信すると作成・送信されてくるトークン
      currency: 'jpy'
    )
  end

  private
  def post_params
    params.require(:post).permit(:title, :lower_limit_price, :upper_limit_price, :content, :company_information, :about_product, :recruitment_background, :job_occupation, :skill, :expected_experience, :attraction_of_company, :attraction_of_job, :attraction_of_environment, :production_deadline, :application_deadline).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
      = f.collection_check_boxes :user_ids, User.all, :id, :name
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.wrapper
  = render 'messages/side_bar'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: 'form', locals: { group: @group }

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title KobeWorks
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    %header.header
      .header__title
        = link_to "kobe works", root_path, class: "header__title--text"
      .header__right
        - if user_signed_in?
          = link_to current_user.name, user_path(current_user), class: "header__right--btn"
          = link_to "メッセージ", groups_path, class: "header__right--btn"
          = link_to "新規案件募集", new_post_path, class: "header__right--btn"
          = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header__right--btn"
        - else
          = link_to "ログイン", new_user_session_path, class: "header__right--btn"
          = link_to "新規登録", new_user_registration_path, class: "header__right--btn"
    .contents
      = yield

app/views/messages/_main_chat.html.haml
.chat-main
  .chat-main__message-head
    .chat-main__message-head__titlebox
      .chat-main__message-head__titlebox__title
        = @group.name
      .chat-main__message-head__titlebox__member
        Member : 
        - @group.users.each do |user|
          = user.name
    .chat-main__message-head__edit
      = link_to "Edit", edit_group_path(@group.id), class: 'main-header__edit-btn'
  .chat-main__message
    = render @messages
  .chat-main__message-form
    = form_for [@group, @message] do |f|
      = f.text_field :content, class: 'form__message', placeholder: 'type a message'
      -# .form__mask
        -# = f.label :image, class: 'form__mask__image' do
          -# = icon('fas', 'image', class: 'icon')
          -# = f.file_field :image, class: 'hidden'
      = f.submit 'Send', class: 'form__submit'

app/views/messages/_message.html.haml
.message{data: {message_id: message.id}}
  .chat-main__message__title
    .chat-main__message__title__name
      = message.user.name
    .chat-main__message__title__date
      = message.created_at
  .chat-main__message__contents
    - if message.content.present?
      %p.lower-message__content
        = message.content
    = image_tag message.image.url, class: 'lower-message__image' if message.image.present?

app/views/messages/_side_bar.html.haml
.side_bar
  .side-header
    .side-header__box
      %p.side-header__box__user-name
        = current_user.name
      %ul.side-header__box__menu
        %li.side-header__box__menu__new__group
          = link_to new_group_path do
            = icon("fas", "edit", class: "icon")
        %li.side-header__box__menu__edit-user
          = link_to edit_user_path(current_user) do
            = icon("fas", "cog", class: "icon")

  .group
    - current_user.groups.each do |group|
      .group-name
        = link_to group_messages_path(group) do
          .group__name
            = group.name

app/views/messages/index.html.haml
.wrapper
  = render "side_bar"
  = render "main_chat"

app/views/posts/_post.html.haml
.content
  .content__left
    .content__left--image
      募集中
  .content__right
    .content__right__top
      = link_to post.title, post_path(post.id), class: "content__right__top--title"
    .content__right__bottom
      .content__right__bottom--userName
        = link_to post.user.name, user_path(post.user), class: "content__right__bottom--userName--btn"
      .content__right__bottom--date
        = post.created_at

app/views/posts/apply.html.haml
.apply
  .apply__box
    .apply__box__theme
      応募内容の確認
    .apply__box__detail
      .apply__box__detail__title
        = @post.title
    .apply__box__pay
      .apply__box__pay__price
        受注金額
      .apply__box__pay__yen
        ¥
        = @post.lower_limit_price
    .apply__box__member
      .apply__box__member__left
        発注元
      .apply__box__member__right
        = @post.user.name
    .apply__box__how
      .apply__box__how__btm
        = link_to confirm_post_path, method: :post do
          応募する

app/views/posts/confirm.html.haml
.confirm
  .confirm_title
    %p 応募が完了しました！
    %p 案件投稿者からのご連絡をお待ちください。

.toplink
  = link_to root_path do
    TOPへ戻る

app/views/posts/edit.html.haml
.content__title
  募集案件の編集
= form_with model: @post, class: :form, local: true do |form|
  = form.text_field :title, placeholder: :案件名, class: :form__title
  = form.text_field :lower_limit_price, placeholder: :提案額, class: :form__title
  = form.text_area :content, placeholder: :業務内容, class: :form__text
  = form.text_area :company_information, placeholder: :企業概要, class: :form__title
  = form.text_area :about_product, placeholder: :プロダクトについて, class: :form__title
  = form.text_area :recruitment_background, placeholder: :募集背景, class: :form__title
  = form.text_field :job_occupation, placeholder: :職種, class: :form__title
  = form.text_area :skill, placeholder: :スキル, class: :form__title
  = form.text_field :expected_experience, placeholder: :求められる経験, class: :form__title
  = form.text_area :attraction_of_company, placeholder: :会社の魅力, class: :form__title
  = form.text_area :attraction_of_job, placeholder: :案件の魅力, class: :form__title
  = form.text_area :attraction_of_environment, placeholder: :環境の魅力, class: :form__title
  応募期限
  = form.date_select :application_deadline, default: { year: 2020, month: 1, day: 1 }
  納期
  = form.date_select :production_deadline, default: { year: 2020, month: 1, day: 1 }
  = form.submit '募集する', class: :form__btn

app/views/posts/index.html.haml
- @posts.each do |post|
  = render partial: "post", locals: { post: post }

app/views/posts/new.html.haml
.content__title
  新規案件の募集

= form_with model: @post, class: :form, local: true do |form|
  = form.text_field :title, placeholder: :案件名, class: :form__title
  = form.number_field :lower_limit_price, placeholder: :提案額, class: :form__lower_limit_price
  = form.text_area :content, placeholder: :業務内容, class: :form__content
  = form.text_area :company_information, placeholder: :企業概要, class: :form__company_information
  = form.text_area :about_product, placeholder: :プロダクトについて, class: :form__about_product
  = form.text_area :recruitment_background, placeholder: :募集背景, class: :form__recruitment_background
  = form.text_area :job_occupation, placeholder: :職種, class: :form__job_occupation
  = form.text_area :skill, placeholder: :スキル, class: :form__skill
  = form.text_area :expected_experience, placeholder: :求められる経験, class: :form__expected_experience
  = form.text_area :attraction_of_company, placeholder: :会社の魅力, class: :form__attraction_of_company
  = form.text_area :attraction_of_job, placeholder: :案件の魅力, class: :form__attraction_of_job
  = form.text_area :attraction_of_environment, placeholder: :環境の魅力, class: :form__attraction_of_environment
  応募期限
  = form.date_select :application_deadline, default: { year: 2020, month: 1, day: 1 }, class: :form__application_deadline
  納期
  = form.date_select :production_deadline, default: { year: 2020, month: 1, day: 1 }, class: :form__production_deadline
  = form.submit '投稿する', class: :form__btn

app/views/posts/show.html.haml
.postTitle
  = @post.title
-# .postDate
-#   = @post.created_at
.postAuthor
- if user_signed_in? && current_user.id == @post.user_id
  .postManage
    = link_to "編集", edit_post_path(@post.id), class: "postManage__edit"
    = link_to "削除", post_path(@post.id), method: :delete, class: "postManage__delete"
    

.jobtable-container
  %dl.demo_dl
    %dt.demo_dt
      %p 業務内容
    %dd.demo_dd 
      = simple_format @post.content
    %dt.demo_dt
      %p 関わるサービス・プロダクト
    %dd.demo_dd 
      ■企業情報
      = simple_format @post.company_information
      ■プロダクトについて
      = simple_format @post.about_product
      ■募集背景
      = simple_format @post.recruitment_background
    %dt.demo_dt
      %p 職種
    %dd.demo_dd
      = @post.job_occupation
    %dt.demo_dt
      %p スキル
    %dd.demo_dd
      = simple_format @post.skill
    %dt.demo_dt
      %p 求められる経験
    %dd.demo_dd
      = simple_format @post.expected_experience
    %dt.demo_dt
      %p 会社の魅力
    %dd.demo_dd
      = simple_format @post.attraction_of_company
    %dt.demo_dt
      %p 仕事の魅力
    %dd.demo_dd
      = simple_format @post.attraction_of_job
    %dt.demo_dt
      %p 環境の魅力
    %dd.demo_dd
      = simple_format @post.attraction_of_environment
    %dt.demo_dt
      %p 納期
    %dd.demo_dd
      = @post.production_deadline
    %dt.demo_dt
      %p 応募期日
    %dd.demo_dd
      = @post.application_deadline
    %dt.demo_dt
      %p 金額
    %dd.demo_dd
      ¥
      = @post.lower_limit_price
.application_form
  - if user_signed_in? && current_user.id == @post.user_id
    .payjp_btn
      = form_with url: purchase_post_path do
        :plain
          <script type="text/javascript" src="https://checkout.pay.jp" class="payjp-button" data-key="公開鍵"></script>
  - else
    .application_btn
      = link_to "応募画面に進む", apply_post_path

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          -# .field-label
          -#   = f.label :nickname
          -# .field-input
          -#   = f.text_field :nickname, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "更新", class: 'btn'

app/views/users/show.html.haml
.postTitle
  = @user.nickname
  さんの募集案件一覧
- @posts.each do |post|
  = render partial: "posts/post", locals: { post: post }